var crkve = {
"type": "FeatureCollection",
"name": "crkve",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "ID": 6, "Naziv crkve": "Crkva svete Katarine Aleksandrijske", "Župa": "Grude", "Mjesto": "Grude (Gomilice)", "Vrsta crkve": "župna crkva", "Godina izgradnje": "1895.", "Web-stranica": "nema", "Značaj": "Površinski i brojem vjernika najveća župa Općine Grude." }, "geometry": { "type": "Point", "coordinates": [ 17.40970408, 43.374663 ] } },
{ "type": "Feature", "properties": { "ID": 14, "Naziv crkve": "Crkva svetog Josipa", "Župa": "Tihaljina", "Mjesto": "Puteševica", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "1989.", "Web-stranica": "nema", "Značaj": "-" }, "geometry": { "type": "Point", "coordinates": [ 17.32561813, 43.31187178 ] } },
{ "type": "Feature", "properties": { "ID": 19, "Naziv crkve": "Crkva sv. Stjepana Prvomučenika od Imote", "Župa": "Gorica-Sovići", "Mjesto": "Gorica (Grabarje)", "Vrsta crkve": "župna crkva", "Godina izgradnje": "1968.", "Web-stranica": "https://zupagoricasovici.info/", "Značaj": "-" }, "geometry": { "type": "Point", "coordinates": [ 17.29178334, 43.4200636 ] } },
{ "type": "Feature", "properties": { "ID": 20, "Naziv crkve": "Stara crkva sv. Stjepana Prvomučenika od Imote", "Župa": "Gorica-Sovići", "Mjesto": "Gorica (Grabarje)", "Vrsta crkve": "stara župna crkva", "Godina izgradnje": "1856.", "Web-stranica": "https://zupagoricasovici.info/", "Značaj": "Najstarija župa Imotske krajine (i Općine Grude). Jedna od najstarijih Crkava u Hrvata (IX. stoljeće) i jedna od najstarijih ranokršćanskih crkava rimske pokrajine Dalmacije (IV. stoljeće), središte Imotske krajine i jedina imotska crkva do rušenja od strane Turaka 1647. Patron župe uzdignut je na čast zaštitnika cijele Imotske krajine te stoga i danas nosi naslov ''crkva sv. Stipana Prvomučenika od Imote'' (suzaštitnik uz BDM od Anđela po oslobođenju Imotske krajine od Turaka 2. kolovoza 1717.)" }, "geometry": { "type": "Point", "coordinates": [ 17.29004569, 43.41948662 ] } },
{ "type": "Feature", "properties": { "ID": 22, "Naziv crkve": "Crkvica sv. Ilije proroka", "Župa": "Tihaljina", "Mjesto": "Tihaljina (Nezdravica)", "Vrsta crkve": "kapelica", "Godina izgradnje": "1889.", "Web-stranica": "nema", "Značaj": "Sv. Ilija slavi se kao zaštitnik župe Tihaljina još od njezina osnutka 1889., a od 1938. kao suzaštitnik jer je otad patron župe Bezgrešno začeće BDM." }, "geometry": { "type": "Point", "coordinates": [ 17.39076486, 43.3136177 ] } },
{ "type": "Feature", "properties": { "ID": 23, "Naziv crkve": "Crkva Bezgrešnog začeća Blažene Djevice Marije", "Župa": "Tihaljina", "Mjesto": "Tihaljina (Nezdravica)", "Vrsta crkve": "župna crkva", "Godina izgradnje": "1938.", "Web-stranica": "nema", "Značaj": "Površinski najveća crkva u Općini Grude." }, "geometry": { "type": "Point", "coordinates": [ 17.39051217, 43.31387846 ] } },
{ "type": "Feature", "properties": { "ID": 25, "Naziv crkve": "Crkva sv. Ante", "Župa": "Raskrižje", "Mjesto": "Cerov Dolac", "Vrsta crkve": "župna crkva", "Godina izgradnje": "1971.", "Web-stranica": "nema", "Značaj": "Župa je dobila ime po svom prostornom smještaju na \"raskrižju\" sela Cerov Dolac (u kojem se crkva nalazi), Pogane Vlake i Borajne koja i čine župu." }, "geometry": { "type": "Point", "coordinates": [ 17.44256415, 43.3281913 ] } },
{ "type": "Feature", "properties": { "ID": 27, "Naziv crkve": "Crkva sv. Ivana Krstitelja", "Župa": "Ružići", "Mjesto": "Ružići (Žlibina)", "Vrsta crkve": "župna crkva", "Godina izgradnje": "1934.", "Web-stranica": "https://zupa-ruzici.com/", "Značaj": "Najstarija aktivna župa u Općini Grude (od 1768.)" }, "geometry": { "type": "Point", "coordinates": [ 17.39742725, 43.34398706 ] } },
{ "type": "Feature", "properties": { "ID": 32, "Naziv crkve": "Crkva sv. Jure", "Župa": "Grude", "Mjesto": "Dragićina", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "2000.", "Web-stranica": "nema", "Značaj": "Crkva je izgrađena 2000. na mjestu stare kapelice podignute u čast sv. Jure 1925. godine." }, "geometry": { "type": "Point", "coordinates": [ 17.44913358, 43.35193823 ] } },
{ "type": "Feature", "properties": { "ID": 33, "Naziv crkve": "Crkva sv. Nikole Tavelića", "Župa": "Ružići", "Mjesto": "Ružići (Marića Strana)", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "1969.", "Web-stranica": "https://zupa-ruzici.com/", "Značaj": "-" }, "geometry": { "type": "Point", "coordinates": [ 17.42983223, 43.3449405 ] } },
{ "type": "Feature", "properties": { "ID": 34, "Naziv crkve": "Zavjetna crkva sv. Izidora", "Župa": "Grude", "Mjesto": "Cere", "Vrsta crkve": "zavjetna kapelica", "Godina izgradnje": "1937.", "Web-stranica": "nema", "Značaj": "Podignuta u čast sv. Izidora Seljaka s nakanom boljeg uroda zemlje." }, "geometry": { "type": "Point", "coordinates": [ 17.39690255, 43.3890041 ] } },
{ "type": "Feature", "properties": { "ID": 39, "Naziv crkve": "Crkva sv. Ante", "Župa": "Drinovci", "Mjesto": "Drinovačko Brdo", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "1950.", "Web-stranica": "nema", "Značaj": "-" }, "geometry": { "type": "Point", "coordinates": [ 17.30259806, 43.32944814 ] } },
{ "type": "Feature", "properties": { "ID": 47, "Naziv crkve": "Crkva sv. Luke", "Župa": "Drinovci", "Mjesto": "Blaževići", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "1988.", "Web-stranica": "nema", "Značaj": "-" }, "geometry": { "type": "Point", "coordinates": [ 17.35102144, 43.37591385 ] } },
{ "type": "Feature", "properties": { "ID": 48, "Naziv crkve": "Crkva sv. Terezije od Djeteta Isusa", "Župa": "Ledinac", "Mjesto": "Ledinac", "Vrsta crkve": "župna crkva", "Godina izgradnje": "1930.", "Web-stranica": "https://www.zupaledinac.com/", "Značaj": "Najstarija crkva na području bivše Jugoslavije i jedna od najstarijih u svijetu općenito podignutih u čast sv. Terezije od Djeteta Isusa (kanonizirana 1925.). Prethodno je postojala kao župa Svetoga Križa (1873.-1878.)." }, "geometry": { "type": "Point", "coordinates": [ 17.48746443, 43.34457115 ] } },
{ "type": "Feature", "properties": { "ID": 55, "Naziv crkve": "Crkva sv. Mihovila Arkanđela", "Župa": "Drinovci", "Mjesto": "Drinovci (Središte)", "Vrsta crkve": "župna crkva", "Godina izgradnje": "1894.", "Web-stranica": "nema", "Značaj": "U vrijeme gradnje, najveća crkva na području Bosne i Hercegovine (nakon katedrale Presvetog Srca Isusova u Sarajevu)." }, "geometry": { "type": "Point", "coordinates": [ 17.32334248, 43.35956545 ] } },
{ "type": "Feature", "properties": { "ID": 79, "Naziv crkve": "Crkva sv. Petra i Pavla", "Župa": "Gorica-Sovići", "Mjesto": "Sovići (Pejića Draga)", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "1970.", "Web-stranica": "https://zupagoricasovici.info/", "Značaj": "Izgrađena na mjestu stare kapelice iz 1937. godine." }, "geometry": { "type": "Point", "coordinates": [ 17.33974241, 43.39960438 ] } },
{ "type": "Feature", "properties": { "ID": 98, "Naziv crkve": "Crkva sv. Marka", "Župa": "Raskrižje", "Mjesto": "Borajna", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "1993.", "Web-stranica": "nema", "Značaj": "-" }, "geometry": { "type": "Point", "coordinates": [ 17.4737338, 43.30767658 ] } },
{ "type": "Feature", "properties": { "ID": 99, "Naziv crkve": "Crkva sv. Petra", "Župa": "Drinovci", "Mjesto": "Drinovci (Ploca-Bili Greb)", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "1971.", "Web-stranica": "nema", "Značaj": "-" }, "geometry": { "type": "Point", "coordinates": [ 17.2881982, 43.35857114 ] } },
{ "type": "Feature", "properties": { "ID": 100, "Naziv crkve": "Crkva sv. Petra i Pavla", "Župa": "Grljevići", "Mjesto": "Borajna", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "1995.", "Web-stranica": "nema", "Značaj": "Crkva pripada župi Grljevići (Grad Ljubuški)." }, "geometry": { "type": "Point", "coordinates": [ 17.48643652, 43.29996841 ] } },
{ "type": "Feature", "properties": { "ID": 103, "Naziv crkve": "Crkva Velike Gospe", "Župa": "Poljica Kozička", "Mjesto": "Jabuka-Mijaca", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "1876.", "Web-stranica": "nema", "Značaj": "Izgrađena je na području Općine Grude, no crkva pripada župi Poljica Kozička (Grad Vrgorac). Koriste ju i stanovnici Jabuke zbog veće udaljenosti župne crkve u Tihaljini." }, "geometry": { "type": "Point", "coordinates": [ 17.3165633, 43.29422641 ] } }
]
}
